### ISSUE TITLE
x509-cert: AMD fTPM certificate is corrupted when parsing from DER

### ISSUE THREAD

**Issue by davidthomaswood** [RustCrypto/formats#1584]
Attempting to parse an EK certificate for an AMD fTPM causes the certificate bytes to change, which results in a certificate that can't be validate.

Test case against f7288cf:

```rust
use x509_cert::{
    der::{Decode as _, Encode as _},
    Certificate,
};

#[test]
fn test_amd_ftpm() {
    let downloaded_bytes = reqwest::blocking::get(format!(
        "https://ftpm.amd.com/pki/aia/46f940b3b7b86267c9cbfb69b90de6ef"
    ))
    .unwrap()
    .bytes()
    .unwrap();

    let cert = Certificate::from_der(&downloaded_bytes).unwrap();

    let encoded_bytes = bytes::Bytes::from(cert.to_der().unwrap());

    assert_eq!(downloaded_bytes, encoded_bytes);
}
```

Which causes the following result:

```
running 1 test
test test_amd_ftpm ... FAILED

failures:

---- test_amd_ftpm stdout ----
thread 'test_amd_ftpm' panicked at tests/round-trip.rs:19:5:
assertion `left == right` failed
  left: b"0\x82\x03_0\x82\x03\x05\xa0\x03\x02\x01\x02\x02\x10F\xf9@\xb3\xb7\xb8bg\xc9\xcb\xfbi\xb9\r\xe6\xef0\n\x06\x08*\x86H\xce=\x04\x03\x020y1\x140\x12\x06\x03U\x04\x0b\x0c\x0bEngineering1\x0b0\t\x06\x03U\x04\x0
6\x13\x02US1\x140\x12\x06\x03U\x04\x07\x0c\x0bSanta Clara1\x0b0\t\x06\x03U\x04\x08\x0c\x02CA1\x1f0\x1d\x06\x03U\x04\n\x0c\x16Advanced Micro Devices1\x100\x0e\x06\x03U\x04\x03\x0c\x07PRG-SSP0\x1e\x17\r220918065734Z\
x17\r470918065734Z0\00Y0\x13\x06\x07*\x86H\xce=\x02\x01\x06\x08*\x86H\xce=\x03\x01\x07\x03B\0\x04aI\x027\xde\xd9\xfce'E[0\x0c|R\x97\xde\x94(B\x98\x05WahE\x19=\x0b\xa3\x84\x84\xfb\xe2Ri\x97\x95Z0\xdbU\n\x98\xf0\xb1\
x1c[\x9b\x0c\xd2b#\xf2\x9f\x01,\xd4F\x17\x02/\x08\xe5\xa3\x82\x01\xe60\x82\x01\xe20\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x05 0\x13\x06\x03U\x1d%\x01\x01\0\x04\t0\x07\x06\x05g\x81\x05\x08\x010X\x06\x08+\
x06\x01\x05\x05\x07\x01\x01\x04L0J0H\x06\x08+\x06\x01\x05\x05\x070\x02\x86<http://ftpm.amd.com/pki/aia/9871E39448FF5B334D41759131D700280,\x06\x03U\x1d\x1f\x04%0#0!\xa0\x1f\xa0\x1d\x86\x1bhttp://ftpm.amd.com/pki/crl
0C\x06\x03U\x1d \x04<0:08\x06\n+\x06\x01\x04\x01\x9cxe\x15\n0*0(\x06\x08+\x06\x01\x05\x05\x07\x02\x01\x16\x1chttps://ftpm.amd.com/pki/cps0\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\x16\xcf\x1c\xcd\xe2\xfcV\x8f\xa5\x97\x
1c\xd5!\xc9\xaer\xf8\xa5\xb9e0\x1f\x06\x03U\x1d#\x04\x180\x16\x80\x14\xe3uho\x18-\x84|\xeb\xe1\xf7\xcez\xed\xa5\xca\xb6\xb6\xbe$0\x0f\x06\x03U\x1d\x13\x01\x01\0\x04\x050\x03\x01\x01\00P\x06\x03U\x1d\x11\x01\x01\xff
\x04F0D\xa4B0@1\x160\x14\x06\x05g\x81\x05\x02\x01\x0c\x0bid:414D44001\x0e0\x0c\x06\x05g\x81\x05\x02\x02\x0c\x03AMD1\x160\x14\x06\x05g\x81\x05\x02\x03\x0c\x0bid:000300010K\x06\x03U\x1d\t\x01\x01\0\x04A0?0\x1e\x06\x0
5g\x81\x05\x02\x101\x150\x13\x0c\x0bid:322E3000\x02\x01\0\x02\x01\x890\x1d\x06\x05g\x81\x05\x02\x121\x140\x12\x02\x01\0\x01\x01\xff\x80\x01\0\x81\x01\0\x82\x01\0\x85\x01\xff0\n\x06\x08*\x86H\xce=\x04\x03\x02\x03H\0
0E\x02 7\xe0]\xf4\x86\xb2=\x11t{\xd3\xc1\xbb\xa9\x81$l\x9d\x9f\xbfpz\xabFA\x0c\xe7\x93\xb3l\x9b\xb1\x02!\0\xe7\x9a\xff\x16+\xa73\xb4\xa4\xf3\xe4\x9c\x90\x1b\xaap\x1e\xb4\xc9~\xfaA-+C\x1d\xa0\xf0P?1\xed"
 right: b"0\x82\x03V0\x82\x02\xfc\xa0\x03\x02\x01\x02\x02\x10F\xf9@\xb3\xb7\xb8bg\xc9\xcb\xfbi\xb9\r\xe6\xef0\n\x06\x08*\x86H\xce=\x04\x03\x020y1\x140\x12\x06\x03U\x04\x0b\x0c\x0bEngineering1\x0b0\t\x06\x03U\x04\x0
6\x13\x02US1\x140\x12\x06\x03U\x04\x07\x0c\x0bSanta Clara1\x0b0\t\x06\x03U\x04\x08\x0c\x02CA1\x1f0\x1d\x06\x03U\x04\n\x0c\x16Advanced Micro Devices1\x100\x0e\x06\x03U\x04\x03\x0c\x07PRG-SSP0\x1e\x17\r220918065734Z\
x17\r470918065734Z0\00Y0\x13\x06\x07*\x86H\xce=\x02\x01\x06\x08*\x86H\xce=\x03\x01\x07\x03B\0\x04aI\x027\xde\xd9\xfce'E[0\x0c|R\x97\xde\x94(B\x98\x05WahE\x19=\x0b\xa3\x84\x84\xfb\xe2Ri\x97\x95Z0\xdbU\n\x98\xf0\xb1\
x1c[\x9b\x0c\xd2b#\xf2\x9f\x01,\xd4F\x17\x02/\x08\xe5\xa3\x82\x01\xdd0\x82\x01\xd90\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x05 0\x10\x06\x03U\x1d%\x04\t0\x07\x06\x05g\x81\x05\x08\x010X\x06\x08+\x06\x01\x0
5\x05\x07\x01\x01\x04L0J0H\x06\x08+\x06\x01\x05\x05\x070\x02\x86<http://ftpm.amd.com/pki/aia/9871E39448FF5B334D41759131D700280,\x06\x03U\x1d\x1f\x04%0#0!\xa0\x1f\xa0\x1d\x86\x1bhttp://ftpm.amd.com/pki/crl0C\x06\x03
U\x1d \x04<0:08\x06\n+\x06\x01\x04\x01\x9cxe\x15\n0*0(\x06\x08+\x06\x01\x05\x05\x07\x02\x01\x16\x1chttps://ftpm.amd.com/pki/cps0\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\x16\xcf\x1c\xcd\xe2\xfcV\x8f\xa5\x97\x1c\xd5!\xc
9\xaer\xf8\xa5\xb9e0\x1f\x06\x03U\x1d#\x04\x180\x16\x80\x14\xe3uho\x18-\x84|\xeb\xe1\xf7\xcez\xed\xa5\xca\xb6\xb6\xbe$0\x0c\x06\x03U\x1d\x13\x04\x050\x03\x01\x01\00P\x06\x03U\x1d\x11\x01\x01\xff\x04F0D\xa4B0@1\x160
\x14\x06\x05g\x81\x05\x02\x01\x0c\x0bid:414D44001\x0e0\x0c\x06\x05g\x81\x05\x02\x02\x0c\x03AMD1\x160\x14\x06\x05g\x81\x05\x02\x03\x0c\x0bid:000300010H\x06\x03U\x1d\t\x04A0?0\x1e\x06\x05g\x81\x05\x02\x101\x150\x13\x
0c\x0bid:322E3000\x02\x01\0\x02\x01\x890\x1d\x06\x05g\x81\x05\x02\x121\x140\x12\x02\x01\0\x01\x01\xff\x80\x01\0\x81\x01\0\x82\x01\0\x85\x01\xff0\n\x06\x08*\x86H\xce=\x04\x03\x02\x03H\00E\x02 7\xe0]\xf4\x86\xb2=\x11
t{\xd3\xc1\xbb\xa9\x81$l\x9d\x9f\xbfpz\xabFA\x0c\xe7\x93\xb3l\x9b\xb1\x02!\0\xe7\x9a\xff\x16+\xa73\xb4\xa4\xf3\xe4\x9c\x90\x1b\xaap\x1e\xb4\xc9~\xfaA-+C\x1d\xa0\xf0P?1\xed"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_amd_ftpm

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.38s
```

Writing the certificate to file additionally gives a certificate that cannot be validated by openssl:

```
$ curl http://ftpm.amd.com/pki/aia/9871E39448FF5B334D41759131D70028 | openssl x509 -in /dev/stdin -inform der -out 9871E39448FF5B334D41759131D70028.pem
$ curl http://ftpm.amd.com/pki/aia/23452201D41C5AB064032BD23F158FEF | openssl x509 -in /dev/stdin -inform der -out 23452201D41C5AB064032BD23F158FEF.pem
$ openssl verify -trusted 23452201D41C5AB064032BD23F158FEF.pem -untrusted 9871E39448FF5B334D41759131D70028.pem ek-cert.pem

error 7 at 0 depth lookup: certificate signature failure
error ek-cert.pem: verification failed
8072808C5D7F0000:error:06880006:asn1 encoding routines:ASN1_item_verify_ctx:EVP lib:crypto/asn1/a_verify.c:221:
```

vs downloading the leaf with openssl:
```
$ curl https://ftpm.amd.com/pki/aia/46f940b3b7b86267c9cbfb69b90de6ef | openssl x509 -in /dev/stdin -inform der -out 46f940b3b7b86267c9cbfb69b90de6ef.pem
$ openssl verify -trusted 23452201D41C5AB064032BD23F158FEF.pem -untrusted 9871E39448FF5B334D41759131D70028.pem 46f940b3b7b86267c9cbfb69b90de6ef.pem
46f940b3b7b86267c9cbfb69b90de6ef.pem: OK
```

**Comment by tarcieri** [comment]
Here's the original cert:

https://lapo.it/asn1js/#MIIDXzCCAwWgAwIBAgIQRvlAs7e4YmfJy_tpuQ3m7zAKBggqhkjOPQQDAjB5MRQwEgYDVQQLDAtFbmdpbmVlcmluZzELMAkGA1UEBhMCVVMxFDASBgNVBAcMC1NhbnRhIENsYXJhMQswCQYDVQQIDAJDQTEfMB0GA1UECgwWQWR2YW5jZWQgTWljcm8gRGV2aWNlczEQMA4GA1UEAwwHUFJHLVNTUDAeFw0yMjA5MTgwNjU3MzRaFw00NzA5MTgwNjU3MzRaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARhSQI33tn8ZSdFWzAMfFKX3pQoQpgFV2FoRRk9C6OEhPviUmmXlVow21UKmPCxHFubDNJiI_KfASzURhcCLwjlo4IB5jCCAeIwDgYDVR0PAQH_BAQDAgUgMBMGA1UdJQEBAAQJMAcGBWeBBQgBMFgGCCsGAQUFBwEBBEwwSjBIBggrBgEFBQcwAoY8aHR0cDovL2Z0cG0uYW1kLmNvbS9wa2kvYWlhLzk4NzFFMzk0NDhGRjVCMzM0RDQxNzU5MTMxRDcwMDI4MCwGA1UdHwQlMCMwIaAfoB2GG2h0dHA6Ly9mdHBtLmFtZC5jb20vcGtpL2NybDBDBgNVHSAEPDA6MDgGCisGAQQBnHhlFQowKjAoBggrBgEFBQcCARYcaHR0cHM6Ly9mdHBtLmFtZC5jb20vcGtpL2NwczAdBgNVHQ4EFgQUFs8czeL8Vo-llxzVIcmucviluWUwHwYDVR0jBBgwFoAU43VobxgthHzr4ffOeu2lyra2viQwDwYDVR0TAQEABAUwAwEBADBQBgNVHREBAf8ERjBEpEIwQDEWMBQGBWeBBQIBDAtpZDo0MTRENDQwMDEOMAwGBWeBBQICDANBTUQxFjAUBgVngQUCAwwLaWQ6MDAwMzAwMDEwSwYDVR0JAQEABEEwPzAeBgVngQUCEDEVMBMMC2lkOjMyMkUzMDAwAgEAAgGJMB0GBWeBBQISMRQwEgIBAAEB_4ABAIEBAIIBAIUB_zAKBggqhkjOPQQDAgNIADBFAiA34F30hrI9EXR708G7qYEkbJ2fv3B6q0ZBDOeTs2ybsQIhAOea_xYrpzO0pPPknJAbqnAetMl--kEtK0MdoPBQPzHt

Here's the one re-encoded by `x509_cert::Certificate`:

https://lapo.it/asn1js/#MIIDVjCCAvygAwIBAgIQRvlAs7e4YmfJy_tpuQ3m7zAKBggqhkjOPQQDAjB5MRQwEgYDVQQLDAtFbmdpbmVlcmluZzELMAkGA1UEBhMCVVMxFDASBgNVBAcMC1NhbnRhIENsYXJhMQswCQYDVQQIDAJDQTEfMB0GA1UECgwWQWR2YW5jZWQgTWljcm8gRGV2aWNlczEQMA4GA1UEAwwHUFJHLVNTUDAeFw0yMjA5MTgwNjU3MzRaFw00NzA5MTgwNjU3MzRaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARhSQI33tn8ZSdFWzAMfFKX3pQoQpgFV2FoRRk9C6OEhPviUmmXlVow21UKmPCxHFubDNJiI_KfASzURhcCLwjlo4IB3TCCAdkwDgYDVR0PAQH_BAQDAgUgMBAGA1UdJQQJMAcGBWeBBQgBMFgGCCsGAQUFBwEBBEwwSjBIBggrBgEFBQcwAoY8aHR0cDovL2Z0cG0uYW1kLmNvbS9wa2kvYWlhLzk4NzFFMzk0NDhGRjVCMzM0RDQxNzU5MTMxRDcwMDI4MCwGA1UdHwQlMCMwIaAfoB2GG2h0dHA6Ly9mdHBtLmFtZC5jb20vcGtpL2NybDBDBgNVHSAEPDA6MDgGCisGAQQBnHhlFQowKjAoBggrBgEFBQcCARYcaHR0cHM6Ly9mdHBtLmFtZC5jb20vcGtpL2NwczAdBgNVHQ4EFgQUFs8czeL8Vo-llxzVIcmucviluWUwHwYDVR0jBBgwFoAU43VobxgthHzr4ffOeu2lyra2viQwDAYDVR0TBAUwAwEBADBQBgNVHREBAf8ERjBEpEIwQDEWMBQGBWeBBQIBDAtpZDo0MTRENDQwMDEOMAwGBWeBBQICDANBTUQxFjAUBgVngQUCAwwLaWQ6MDAwMzAwMDEwSAYDVR0JBEEwPzAeBgVngQUCEDEVMBMMC2lkOjMyMkUzMDAwAgEAAgGJMB0GBWeBBQISMRQwEgIBAAEB_4ABAIEBAIIBAIUB_zAKBggqhkjOPQQDAgNIADBFAiA34F30hrI9EXR708G7qYEkbJ2fv3B6q0ZBDOeTs2ybsQIhAOea_xYrpzO0pPPknJAbqnAetMl--kEtK0MdoPBQPzHt

All of the extensions in the original cert appear to have the critical bit set, but only some of them do in the reserialized version. Namely the second and last extensions do NOT have it set.

**Comment by carl-wallace** [comment]
The original cert is not DER encoded. So, when reencoding with DER, you get different bytes and the signature is busted. This is common enough that it’s generally a good idea to avoid reencoding when verifying signatures. The issue in this case is the encoding of DEFAULT values for the critical field in a few extensions. Here’s basic constraints from the original cert:

 

605  15:         SEQUENCE {

607   3:           OBJECT IDENTIFIER basicConstraints (2 5 29 19)

612   1:           BOOLEAN FALSE

615   5:           OCTET STRING, encapsulates {

617   3:             SEQUENCE {

619   1:               BOOLEAN FALSE

       :               }

       :             }

       :           }

 

Here’s basicConstraints from the reencoded version:

 

602  12:         SEQUENCE {

604   3:           OBJECT IDENTIFIER basicConstraints (2 5 29 19)

609   5:           OCTET STRING, encapsulates {

611   3:             SEQUENCE {

613   1:               BOOLEAN FALSE

       :               }

       :             }

       :           }

 

The definition of Extension is this:

 

   Extension  ::=  SEQUENCE  {

        extnID      OBJECT IDENTIFIER,

        critical    BOOLEAN DEFAULT FALSE,

        extnValue   OCTET STRING

                    -- contains the DER encoding of an ASN.1 value

                    -- corresponding to the extension type identified

                    -- by extnID

        }

 

Since this extension has FALSE as the value for critical and that value is the DEFAULT, the field is omitted when DER encoding. If you want to verify a cert signature you could use a structure like the below. This refrains from parsing the TBSCertificate field so the value can be used to verify the signature without reencoding.

 

pub struct DeferDecodeSigned {
    /// tbsCertificate       TBSCertificate,
    pub tbs_field: Vec<u8>,
    /// signatureAlgorithm   AlgorithmIdentifier,
    pub signature_algorithm: AlgorithmIdentifierOwned,
    /// signature            BIT STRING
    pub signature: BitString,
}

 

 

From: David Wood ***@***.***>
Reply-To: RustCrypto/formats ***@***.***>
Date: Wednesday, October 23, 2024 at 2:20 PM
To: RustCrypto/formats ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RustCrypto/formats] x509-cert: AMD fTPM certificate is corrupted when parsing from DER (Issue #1584)

 

Attempting to parse an EK certificate for an AMD fTPM causes the certificate bytes to change, which results in a certificate that can't be validate.

Test case against f7288cf:

use x509_cert::{
    der::{Decode as _, Encode as _},
    Certificate,
};
 
#[test]
fn test_amd_ftpm() {
    let downloaded_bytes = reqwest::blocking::get(format!(
        "https://ftpm.amd.com/pki/aia/46f940b3b7b86267c9cbfb69b90de6ef"
    ))
    .unwrap()
    .bytes()
    .unwrap();
 
    let cert = Certificate::from_der(&downloaded_bytes).unwrap();
 
    let encoded_bytes = bytes::Bytes::from(cert.to_der().unwrap());
 
    assert_eq!(downloaded_bytes, encoded_bytes);
}
Which causes the following result:
running 1 test
test test_amd_ftpm ... FAILED
 
failures:
 
---- test_amd_ftpm stdout ----
thread 'test_amd_ftpm' panicked at tests/round-trip.rs:19:5:
assertion `left == right` failed
  left: b"0\x82\x03_0\x82\x03\x05\xa0\x03\x02\x01\x02\x02\x10F\xf9@\xb3\xb7\xb8bg\xc9\xcb\xfbi\xb9\r\xe6\xef0\n\x06\x08*\x86H\xce=\x04\x03\x020y1\x140\x12\x06\x03U\x04\x0b\x0c\x0bEngineering1\x0b0\t\x06\x03U\x04\x0
6\x13\x02US1\x140\x12\x06\x03U\x04\x07\x0c\x0bSanta Clara1\x0b0\t\x06\x03U\x04\x08\x0c\x02CA1\x1f0\x1d\x06\x03U\x04\n\x0c\x16Advanced Micro Devices1\x100\x0e\x06\x03U\x04\x03\x0c\x07PRG-SSP0\x1e\x17\r220918065734Z\
x17\r470918065734Z0\00Y0\x13\x06\x07*\x86H\xce=\x02\x01\x06\x08*\x86H\xce=\x03\x01\x07\x03B\0\x04aI\x027\xde\xd9\xfce'E[0\x0c|R\x97\xde\x94(B\x98\x05WahE\x19=\x0b\xa3\x84\x84\xfb\xe2Ri\x97\x95Z0\xdbU\n\x98\xf0\xb1\
x1c[\x9b\x0c\xd2b#\xf2\x9f\x01,\xd4F\x17\x02/\x08\xe5\xa3\x82\x01\xe60\x82\x01\xe20\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x05 0\x13\x06\x03U\x1d%\x01\x01\0\x04\t0\x07\x06\x05g\x81\x05\x08\x010X\x06\x08+\
x06\x01\x05\x05\x07\x01\x01\x04L0J0H\x06\x08+\x06\x01\x05\x05\x070\x02\x86<http://ftpm.amd.com/pki/aia/9871E39448FF5B334D41759131D700280,\x06\x03U\x1d\x1f\x04%0#0!\xa0\x1f\xa0\x1d\x86\x1bhttp://ftpm.amd.com/pki/crl
0C\x06\x03U\x1d \x04<0:08\x06\n+\x06\x01\x04\x01\x9cxe\x15\n0*0(\x06\x08+\x06\x01\x05\x05\x07\x02\x01\x16\x1chttps://ftpm.amd.com/pki/cps0\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\x16\xcf\x1c\xcd\xe2\xfcV\x8f\xa5\x97\x
1c\xd5!\xc9\xaer\xf8\xa5\xb9e0\x1f\x06\x03U\x1d#\x04\x180\x16\x80\x14\xe3uho\x18-\x84|\xeb\xe1\xf7\xcez\xed\xa5\xca\xb6\xb6\xbe$0\x0f\x06\x03U\x1d\x13\x01\x01\0\x04\x050\x03\x01\x01\00P\x06\x03U\x1d\x11\x01\x01\xff
***@***.***\x160\x14\x06\x05g\x81\x05\x02\x01\x0c\x0bid:414D44001\x0e0\x0c\x06\x05g\x81\x05\x02\x02\x0c\x03AMD1\x160\x14\x06\x05g\x81\x05\x02\x03\x0c\x0bid:000300010K\x06\x03U\x1d\t\x01\x01\0\x04A0?0\x1e\x06\x0
5g\x81\x05\x02\x101\x150\x13\x0c\x0bid:322E3000\x02\x01\0\x02\x01\x890\x1d\x06\x05g\x81\x05\x02\x121\x140\x12\x02\x01\0\x01\x01\xff\x80\x01\0\x81\x01\0\x82\x01\0\x85\x01\xff0\n\x06\x08*\x86H\xce=\x04\x03\x02\x03H\0
0E\x02 7\xe0]\xf4\x86\xb2=\x11t{\xd3\xc1\xbb\xa9\x81$l\x9d\x9f\xbfpz\xabFA\x0c\xe7\x93\xb3l\x9b\xb1\x02!\0\xe7\x9a\xff\x16+\xa73\xb4\xa4\xf3\xe4\x9c\x90\x1b\xaap\x1e\xb4\xc9~\xfaA-+C\x1d\xa0\xf0P?1\xed"
 right: b"0\x82\x03V0\x82\x02\xfc\xa0\x03\x02\x01\x02\x02\x10F\xf9@\xb3\xb7\xb8bg\xc9\xcb\xfbi\xb9\r\xe6\xef0\n\x06\x08*\x86H\xce=\x04\x03\x020y1\x140\x12\x06\x03U\x04\x0b\x0c\x0bEngineering1\x0b0\t\x06\x03U\x04\x0
6\x13\x02US1\x140\x12\x06\x03U\x04\x07\x0c\x0bSanta Clara1\x0b0\t\x06\x03U\x04\x08\x0c\x02CA1\x1f0\x1d\x06\x03U\x04\n\x0c\x16Advanced Micro Devices1\x100\x0e\x06\x03U\x04\x03\x0c\x07PRG-SSP0\x1e\x17\r220918065734Z\
x17\r470918065734Z0\00Y0\x13\x06\x07*\x86H\xce=\x02\x01\x06\x08*\x86H\xce=\x03\x01\x07\x03B\0\x04aI\x027\xde\xd9\xfce'E[0\x0c|R\x97\xde\x94(B\x98\x05WahE\x19=\x0b\xa3\x84\x84\xfb\xe2Ri\x97\x95Z0\xdbU\n\x98\xf0\xb1\
x1c[\x9b\x0c\xd2b#\xf2\x9f\x01,\xd4F\x17\x02/\x08\xe5\xa3\x82\x01\xdd0\x82\x01\xd90\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x05 0\x10\x06\x03U\x1d%\x04\t0\x07\x06\x05g\x81\x05\x08\x010X\x06\x08+\x06\x01\x0
5\x05\x07\x01\x01\x04L0J0H\x06\x08+\x06\x01\x05\x05\x070\x02\x86<http://ftpm.amd.com/pki/aia/9871E39448FF5B334D41759131D700280,\x06\x03U\x1d\x1f\x04%0#0!\xa0\x1f\xa0\x1d\x86\x1bhttp://ftpm.amd.com/pki/crl0C\x06\x03
U\x1d \x04<0:08\x06\n+\x06\x01\x04\x01\x9cxe\x15\n0*0(\x06\x08+\x06\x01\x05\x05\x07\x02\x01\x16\x1chttps://ftpm.amd.com/pki/cps0\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\x16\xcf\x1c\xcd\xe2\xfcV\x8f\xa5\x97\x1c\xd5!\xc
***@***.***\x160
\x14\x06\x05g\x81\x05\x02\x01\x0c\x0bid:414D44001\x0e0\x0c\x06\x05g\x81\x05\x02\x02\x0c\x03AMD1\x160\x14\x06\x05g\x81\x05\x02\x03\x0c\x0bid:000300010H\x06\x03U\x1d\t\x04A0?0\x1e\x06\x05g\x81\x05\x02\x101\x150\x13\x
0c\x0bid:322E3000\x02\x01\0\x02\x01\x890\x1d\x06\x05g\x81\x05\x02\x121\x140\x12\x02\x01\0\x01\x01\xff\x80\x01\0\x81\x01\0\x82\x01\0\x85\x01\xff0\n\x06\x08*\x86H\xce=\x04\x03\x02\x03H\00E\x02 7\xe0]\xf4\x86\xb2=\x11
t{\xd3\xc1\xbb\xa9\x81$l\x9d\x9f\xbfpz\xabFA\x0c\xe7\x93\xb3l\x9b\xb1\x02!\0\xe7\x9a\xff\x16+\xa73\xb4\xa4\xf3\xe4\x9c\x90\x1b\xaap\x1e\xb4\xc9~\xfaA-+C\x1d\xa0\xf0P?1\xed"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 
 
failures:
    test_amd_ftpm
 
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.38s
Writing the certificate to file additionally gives a certificate that cannot be validated by openssl:
$ curl http://ftpm.amd.com/pki/aia/9871E39448FF5B334D41759131D70028 | openssl x509 -in /dev/stdin -inform der -out 9871E39448FF5B334D41759131D70028.pem
$ curl http://ftpm.amd.com/pki/aia/23452201D41C5AB064032BD23F158FEF | openssl x509 -in /dev/stdin -inform der -out 23452201D41C5AB064032BD23F158FEF.pem
$ openssl verify -trusted 23452201D41C5AB064032BD23F158FEF.pem -untrusted 9871E39448FF5B334D41759131D70028.pem ek-cert.pem
 
error 7 at 0 depth lookup: certificate signature failure
error ek-cert.pem: verification failed
8072808C5D7F0000:error:06880006:asn1 encoding routines:ASN1_item_verify_ctx:EVP lib:crypto/asn1/a_verify.c:221:
vs downloading the leaf with openssl:
$ curl https://ftpm.amd.com/pki/aia/46f940b3b7b86267c9cbfb69b90de6ef | openssl x509 -in /dev/stdin -inform der -out 46f940b3b7b86267c9cbfb69b90de6ef.pem
$ openssl verify -trusted 23452201D41C5AB064032BD23F158FEF.pem -untrusted 9871E39448FF5B334D41759131D70028.pem 46f940b3b7b86267c9cbfb69b90de6ef.pem
46f940b3b7b86267c9cbfb69b90de6ef.pem: OK

**Comment by davidthomaswood** [comment]
Ah, I guess I'd been assuming that the x509-cert crate kept around a copy of the unparsed input, but it makes sense for it to be creating the DER output from Rust again when needed. 

Thank you for your speedy response, I've been able to get my verification working using a slightly modified version of your example struct:

```rust
pub struct DeferDecodeSigned {
    /// tbsCertificate       TBSCertificate,
    pub tbs_field: der::Any,
    /// signatureAlgorithm   AlgorithmIdentifier,
    pub signature_algorithm: AlgorithmIdentifierOwned,
    /// signature            BIT STRING
    pub signature: BitString,
}
```
