### ISSUE TITLE
pkcs8 & pkcs1 should not have duplicate implementations for Decodeable/Encodeable

### ISSUE THREAD

**Issue by Scarjit** [RustCrypto/formats#419]
This is related to #410.

The crate could use the Integer proc macro, if pkcs8's Version enum get's a repr attribute.

This would remove this duplicate code:

## pkcs1
https://github.com/RustCrypto/formats/blob/9ac528187ac823bf106b2eaf5a36216a0dccb958/pkcs1/src/version.rs#L54-L72

## pkcs8
https://github.com/RustCrypto/formats/blob/9ac528187ac823bf106b2eaf5a36216a0dccb958/pkcs8/src/version.rs#L28-L42
https://github.com/RustCrypto/formats/blob/9ac528187ac823bf106b2eaf5a36216a0dccb958/pkcs8/src/version.rs#L61-L63

**Comment by tarcieri** [comment]
FWIW, there's already two open PRs about this: #410 #363

The reason these crates don't use custom derive for this is to avoid pulling in the `der_derive`, `proc_macro2`, `proc-macro-error`, `quote`, and `syn` crates to eliminate a dozen lines of duplicated code.

`pkcs1` and `pkcs8` are hard dependencies of several crates which otherwise don't have a dependency on the Rust proc macro stack. `syn` in particular has not-insignificant compile times.
