### ISSUE TITLE
Why would EncodePrivateKey::to_pkcs8_der fail?

### ISSUE THREAD

**Issue by randombit** [RustCrypto/formats#912]
``EncodePrivateKey::to_pkcs8_der`` returns a `Result`, but it is not clear (and not documented) how or why this function might fail. Is it safe to `.expect` the result of `to_pkcs8_der`?

**Comment by tarcieri** [comment]
All of the crates in this repo have been written to support a no-panic profile (although lacking the tooling to do so, we don't yet have static enforcement of that).

To that end all methods are fallible to handle potential implementation errors and propagate them as `Result` rather than panicking.

It's fine to use `.expect` to panic in these cases if you'd prefer not to handle the error.

**Comment by randombit** [comment]
Sorry maybe my question was unclear but - what error might this function return? What would handling the error look like? If I have some key (say a `k256::SigningKey`) and `to_pkcs8_der` fails, does this imply the key is invalid?

**Comment by tarcieri** [comment]
As a trait method, that's going to vary depending on the concrete implementation.

That said, the main ones you can probably expect are `Error::Asn1`, where the encoder contains a bug which is leading to an encoding error.
